# Generated by Django 2.1.5 on 2019-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['weight']},
        ),
        migrations.AddField(
            model_name='choice',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
