# Generated by Django 2.1.5 on 2019-01-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_usercount_create_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_game_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='activation_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
